//
//  Class.swift
//  AggiePal
//
//  Created by Mohamed Ali Boutaleb on 5/20/23.
//

import Foundation

struct Class: Identifiable {
    let id = UUID()
    let crn: Int
    let courseCode: String
    let courseName: String
    let open: Int
    let reserved: Int
    let waitlist: Int
    let units: Int
    let instructor: String
    let rmpRating: Double
    let courseNotes: String
    let description: String
    let subject: String
    let prerequisities: String
    let newGECourses: String
    let finalExam: Date
    let courseMaterials: String
    let courseDropDate: Date
    let warning: (cantJoinClass: Bool , why: String)
}

struct Classes {
    static let ecs: [Class] = [
        Class(crn: 53048, courseCode: "ECS 012 001", courseName: "Introduction to Media Computation", open: 80, reserved: 0, waitlist: 0, units: 4, instructor: "TBA", rmpRating: 0.0,
              courseNotes: "PASS 1: OPEN TO CINEMA & DIGITAL MEDIA MAJORS",
              description: "Introduction to key computational ideas necessary to understand and produce digital media. Fundamentals of programming and analysis of how media are represented and transmitted in digital form. Aimed primarily at non-computer science students.",
              subject: "Engineering Computer Science", prerequisities: "", newGECourses: "AH, QL, SE, VL",
              finalExam: Calendar.current.date(from: DateComponents(year: 2023, month: 12, day: 12))!,
              courseMaterials: "https://ucdavisstores.com/SelectTermDept?reg=7", courseDropDate: Calendar.current.date(from: DateComponents(year: 2023, month: 10, day: 10))!,
              warning: (false , "")),
        
        Class(crn: 30314, courseCode: "ECS 020 A01", courseName: "Discrete Mathematics for Computer Science", open: 54, reserved: 4, waitlist: 0, units: 4, instructor: "M. Franklin", rmpRating: 1.6,
              courseNotes: "**PASS 1: OPEN TO COMPUTER SCIENCE, COMPUTER SCIENCE AND ENGINEERING, COMPUTER ENGINEERING, AND COGNITIVES SCIENCE MAJORS** \n\n **RESERVED SEATS HELD FOR NEW FRESHMEN AND TRANSFER STUDENTS** \n\n **THIS COURSE DOES NOT HAVE A WAITLIST DURING PASS 1 FOR THE FALL TERM**",
              description: "Discrete mathematics of particular utility to computer science. Proofs by induction. Propositional and first-order logic. Sets, functions, and relations. Big-O and related notations. Recursion and solutions of recurrence relations. Combinatorics. Probability on finite probability spaces. Graph theory.",
              subject: "Engineering Computer Science", prerequisities: "MAT 016A C- or better or MAT 017A C- or better or MAT 021A C- or better", newGECourses: "QL, SE",
              finalExam: Calendar.current.date(from: DateComponents(year: 2023, month: 12, day: 12))!,
              courseMaterials: "https://ucdavisstores.com/SelectTermDept?reg=7", courseDropDate: Calendar.current.date(from: DateComponents(year: 2023, month: 10, day: 10))!,
              warning: (true , "Already passed the class.")),
        
        Class(crn: 30315, courseCode: "ECS 020 A02", courseName: "Discrete Mathematics for Computer Science", open: 52, reserved: 3, waitlist: 0, units: 4, instructor: "M. Franklin", rmpRating: 1.6,
              courseNotes: "**PASS 1: OPEN TO COMPUTER SCIENCE, COMPUTER SCIENCE AND ENGINEERING, COMPUTER ENGINEERING, AND COGNITIVES SCIENCE MAJORS** \n\n **RESERVED SEATS HELD FOR NEW FRESHMEN AND TRANSFER STUDENTS** \n\n **THIS COURSE DOES NOT HAVE A WAITLIST DURING PASS 1 FOR THE FALL TERM**",
              description: "Discrete mathematics of particular utility to computer science. Proofs by induction. Propositional and first-order logic. Sets, functions, and relations. Big-O and related notations. Recursion and solutions of recurrence relations. Combinatorics. Probability on finite probability spaces. Graph theory.",
              subject: "Engineering Computer Science", prerequisities: "MAT 016A C- or better or MAT 017A C- or better or MAT 021A C- or better", newGECourses: "QL, SE",
              finalExam: Calendar.current.date(from: DateComponents(year: 2023, month: 12, day: 12))!,
              courseMaterials: "https://ucdavisstores.com/SelectTermDept?reg=7", courseDropDate: Calendar.current.date(from: DateComponents(year: 2023, month: 10, day: 10))!,
              warning: (true , "Already passed the class.")),
        
        Class(crn: 30316, courseCode: "ECS 020 A03", courseName: "Discrete Mathematics for Computer Science", open: 56, reserved: 3, waitlist: 0, units: 4, instructor: "M. Franklin", rmpRating: 1.6,
              courseNotes: "**PASS 1: OPEN TO COMPUTER SCIENCE, COMPUTER SCIENCE AND ENGINEERING, COMPUTER ENGINEERING, AND COGNITIVES SCIENCE MAJORS** \n\n **RESERVED SEATS HELD FOR NEW FRESHMEN AND TRANSFER STUDENTS** \n\n **THIS COURSE DOES NOT HAVE A WAITLIST DURING PASS 1 FOR THE FALL TERM**",
              description: "Discrete mathematics of particular utility to computer science. Proofs by induction. Propositional and first-order logic. Sets, functions, and relations. Big-O and related notations. Recursion and solutions of recurrence relations. Combinatorics. Probability on finite probability spaces. Graph theory.",
              subject: "Engineering Computer Science", prerequisities: "MAT 016A C- or better or MAT 017A C- or better or MAT 021A C- or better", newGECourses: "QL, SE",
              finalExam: Calendar.current.date(from: DateComponents(year: 2023, month: 12, day: 12))!,
              courseMaterials: "https://ucdavisstores.com/SelectTermDept?reg=7", courseDropDate: Calendar.current.date(from: DateComponents(year: 2023, month: 10, day: 10))!,
              warning: (true , "Already passed the class.")),
        
        Class(crn: 30317, courseCode: "ECS 020 A04", courseName: "Discrete Mathematics for Computer Science", open: 55, reserved: 5, waitlist: 0, units: 4, instructor: "M. Franklin", rmpRating: 1.6,
              courseNotes: "**PASS 1: OPEN TO COMPUTER SCIENCE, COMPUTER SCIENCE AND ENGINEERING, COMPUTER ENGINEERING, AND COGNITIVES SCIENCE MAJORS** \n\n **RESERVED SEATS HELD FOR NEW FRESHMEN AND TRANSFER STUDENTS** \n\n **THIS COURSE DOES NOT HAVE A WAITLIST DURING PASS 1 FOR THE FALL TERM**",
              description: "Discrete mathematics of particular utility to computer science. Proofs by induction. Propositional and first-order logic. Sets, functions, and relations. Big-O and related notations. Recursion and solutions of recurrence relations. Combinatorics. Probability on finite probability spaces. Graph theory.",
              subject: "Engineering Computer Science", prerequisities: "MAT 016A C- or better or MAT 017A C- or better or MAT 021A C- or better", newGECourses: "QL, SE",
              finalExam: Calendar.current.date(from: DateComponents(year: 2023, month: 12, day: 12))!,
              courseMaterials: "https://ucdavisstores.com/SelectTermDept?reg=7", courseDropDate: Calendar.current.date(from: DateComponents(year: 2023, month: 10, day: 10))!,
              warning: (true , "Already passed the class.")),
        
        Class(crn: 30318, courseCode: "ECS 032A A01", courseName: "Introduction to Programming", open: 23, reserved: 27, waitlist: 0, units: 4, instructor: "E. Solares", rmpRating: 3.9,
              courseNotes: "**OPEN TO UNDERGRADUATE STUDENTS ONLY**\n\n**RESERVED SEATS HELD FOR NEW FRESHMEN AND TRANSFER STUDENTS**\n\n**THIS COURSE DOES NOT HAVE A WAITLIST DURING PASS 1 FOR THE FALL TERM**",
              description: "Introduction to programming and problem solving in Python. Aimed primarily at non-major students.",
              subject: "Engineering Computer Science", prerequisities: "N/A", newGECourses: "SE",
              finalExam: Calendar.current.date(from: DateComponents(year: 2023, month: 12, day: 13))!,
              courseMaterials: "https://ucdavisstores.com/SelectTermDept?reg=7",
              courseDropDate: Calendar.current.date(from: DateComponents(year: 2023, month: 10, day: 10))!,
              warning: (true, "Already passed the class.")),
        
        Class(crn: 30319, courseCode: "ECS 032A A02", courseName: "Introduction to Programming", open: 27, reserved: 27, waitlist: 0, units: 4, instructor: "E. Solares", rmpRating: 3.9,
              courseNotes: "**OPEN TO UNDERGRADUATE STUDENTS ONLY**\n\n**RESERVED SEATS HELD FOR NEW FRESHMEN AND TRANSFER STUDENTS**\n\n**THIS COURSE DOES NOT HAVE A WAITLIST DURING PASS 1 FOR THE FALL TERM**",
              description: "Introduction to programming and problem solving in Python. Aimed primarily at non-major students.",
              subject: "Engineering Computer Science", prerequisities: "N/A", newGECourses: "SE",
              finalExam: Calendar.current.date(from: DateComponents(year: 2023, month: 12, day: 13))!,
              courseMaterials: "https://ucdavisstores.com/SelectTermDept?reg=7",
              courseDropDate: Calendar.current.date(from: DateComponents(year: 2023, month: 10, day: 10))!,
              warning: (true, "Already passed the class.")),
        
        Class(crn: 30320, courseCode: "ECS 032A A03", courseName: "Introduction to Programming", open: 26, reserved: 28, waitlist: 0, units: 4, instructor: "E. Solares", rmpRating: 3.9,
              courseNotes: "**OPEN TO UNDERGRADUATE STUDENTS ONLY**\n\n**RESERVED SEATS HELD FOR NEW FRESHMEN AND TRANSFER STUDENTS**\n\n**THIS COURSE DOES NOT HAVE A WAITLIST DURING PASS 1 FOR THE FALL TERM**",
              description: "Introduction to programming and problem solving in Python. Aimed primarily at non-major students.",
              subject: "Engineering Computer Science", prerequisities: "N/A", newGECourses: "SE",
              finalExam: Calendar.current.date(from: DateComponents(year: 2023, month: 12, day: 13))!,
              courseMaterials: "https://ucdavisstores.com/SelectTermDept?reg=7",
              courseDropDate: Calendar.current.date(from: DateComponents(year: 2023, month: 10, day: 10))!,
              warning: (true, "Already passed the class.")),
        
        Class(crn: 30323, courseCode: "ECS 032A B01", courseName: "Introduction to Programming", open: 19, reserved: 28, waitlist: 0, units: 4, instructor: "K. Stevens", rmpRating: 5.0,
              courseNotes: "**OPEN TO UNDERGRADUATE STUDENTS ONLY**\n\n**RESERVED SEATS HELD FOR NEW FRESHMEN AND TRANSFER STUDENTS**\n\n**THIS COURSE DOES NOT HAVE A WAITLIST DURING PASS 1 FOR THE FALL TERM**",
              description: "Introduction to programming and problem solving in Python. Aimed primarily at non-major students.",
              subject: "Engineering Computer Science", prerequisities: "N/A", newGECourses: "SE",
              finalExam: Calendar.current.date(from: DateComponents(year: 2023, month: 12, day: 13))!,
              courseMaterials: "https://ucdavisstores.com/SelectTermDept?reg=7",
              courseDropDate: Calendar.current.date(from: DateComponents(year: 2023, month: 10, day: 10))!,
              warning: (true, "Already passed the class.")),
        
        Class(crn: 30324, courseCode: "ECS 032A B02", courseName: "Introduction to Programming", open: 5, reserved: 28, waitlist: 0, units: 4, instructor: "K. Stevens", rmpRating: 5.0,
              courseNotes: "**OPEN TO UNDERGRADUATE STUDENTS ONLY**\n\n**RESERVED SEATS HELD FOR NEW FRESHMEN AND TRANSFER STUDENTS**\n\n**THIS COURSE DOES NOT HAVE A WAITLIST DURING PASS 1 FOR THE FALL TERM**",
              description: "Introduction to programming and problem solving in Python. Aimed primarily at non-major students.",
              subject: "Engineering Computer Science", prerequisities: "N/A", newGECourses: "SE",
              finalExam: Calendar.current.date(from: DateComponents(year: 2023, month: 12, day: 13))!,
              courseMaterials: "https://ucdavisstores.com/SelectTermDept?reg=7",
              courseDropDate: Calendar.current.date(from: DateComponents(year: 2023, month: 10, day: 10))!,
              warning: (true, "Already passed the class.")),
        
        Class(crn: 30325, courseCode: "ECS 032A B32", courseName: "Introduction to Programming", open: 0, reserved: 28, waitlist: 0, units: 4, instructor: "K. Stevens", rmpRating: 5.0,
              courseNotes: "**OPEN TO UNDERGRADUATE STUDENTS ONLY**\n\n**RESERVED SEATS HELD FOR NEW FRESHMEN AND TRANSFER STUDENTS**\n\n**THIS COURSE DOES NOT HAVE A WAITLIST DURING PASS 1 FOR THE FALL TERM**",
              description: "Introduction to programming and problem solving in Python. Aimed primarily at non-major students.",
              subject: "Engineering Computer Science", prerequisities: "N/A", newGECourses: "SE",
              finalExam: Calendar.current.date(from: DateComponents(year: 2023, month: 12, day: 13))!,
              courseMaterials: "https://ucdavisstores.com/SelectTermDept?reg=7",
              courseDropDate: Calendar.current.date(from: DateComponents(year: 2023, month: 10, day: 10))!,
              warning: (true, "Already passed the class.")),
        
        Class(crn: 30326, courseCode: "ECS 032B A01", courseName: "Introduction to Data Structures", open: 46, reserved: 0, waitlist: 0, units: 4, instructor: "V. Bhaskar", rmpRating: 2.0,
              courseNotes: "** NOT OPEN TO COMPUTER SCIENCE AND COMPUTER SCIENCE & ENGINEERING MAJORS **",
              description: "Design and analysis of data structures using Python; trees, heaps, searching, sorting, and graphs.",
              subject: "Engineering Computer Science", prerequisities: "ECS 010 C- or better or ECS 030 C- or better or ECS 032A C- or better or ECS 036A C- or better", newGECourses: "SE",
              finalExam: Calendar.current.date(from: DateComponents(year: 2023, month: 12, day: 12))!,
              courseMaterials: "https://ucdavisstores.com/SelectTermDept?reg=7",
              courseDropDate: Calendar.current.date(from: DateComponents(year: 2023, month: 10, day: 10))!,
              warning: (true, "Already passed the class.")),
        
        Class(crn: 30326, courseCode: "ECS 032B A02", courseName: "Introduction to Data Structures", open: 57, reserved: 0, waitlist: 0, units: 4, instructor: "V. Bhaskar", rmpRating: 2.0,
              courseNotes: "** NOT OPEN TO COMPUTER SCIENCE AND COMPUTER SCIENCE & ENGINEERING MAJORS **",
              description: "Design and analysis of data structures using Python; trees, heaps, searching, sorting, and graphs.",
              subject: "Engineering Computer Science", prerequisities: "ECS 010 C- or better or ECS 030 C- or better or ECS 032A C- or better or ECS 036A C- or better", newGECourses: "SE",
              finalExam: Calendar.current.date(from: DateComponents(year: 2023, month: 12, day: 12))!,
              courseMaterials: "https://ucdavisstores.com/SelectTermDept?reg=7",
              courseDropDate: Calendar.current.date(from: DateComponents(year: 2023, month: 10, day: 10))!,
              warning: (true, "Already passed the class.")),
        
        Class(crn: 30327, courseCode: "ECS 032B A03", courseName: "Introduction to Data Structures", open: 54, reserved: 0, waitlist: 0, units: 4, instructor: "V. Bhaskar", rmpRating: 2.0,
              courseNotes: "** NOT OPEN TO COMPUTER SCIENCE AND COMPUTER SCIENCE & ENGINEERING MAJORS **",
              description: "Design and analysis of data structures using Python; trees, heaps, searching, sorting, and graphs.",
              subject: "Engineering Computer Science", prerequisities: "ECS 010 C- or better or ECS 030 C- or better or ECS 032A C- or better or ECS 036A C- or better", newGECourses: "SE",
              finalExam: Calendar.current.date(from: DateComponents(year: 2023, month: 12, day: 12))!,
              courseMaterials: "https://ucdavisstores.com/SelectTermDept?reg=7",
              courseDropDate: Calendar.current.date(from: DateComponents(year: 2023, month: 10, day: 10))!,
              warning: (true, "Already passed the class.")),
        
        Class(crn: 52382, courseCode: "ECS 032C A01", courseName: "Implementation of Data Structures in C", open: 19, reserved: 0, waitlist: 0, units: 4, instructor: "D. Posnett", rmpRating: 2.0,
              courseNotes: "** NOT OPEN TO COMPUTER SCIENCE AND COMPUTER SCIENCE & ENGINEERING MAJORS **",
              description: "Programming in the C language. Use of basic UNIX tools. Writing good programs of increased complexity and efficiency. Implementation of data structures in C.",
              subject: "Engineering Computer Science", prerequisities: "ECS 032B C- or better", newGECourses: "SE",
              finalExam: Calendar.current.date(from: DateComponents(year: 2023, month: 12, day: 14))!,
              courseMaterials: "https://ucdavisstores.com/SelectTermDept?reg=7",
              courseDropDate: Calendar.current.date(from: DateComponents(year: 2023, month: 10, day: 24))!,
              warning: (true, "Already passed the class.")),
        
        Class(crn: 52383, courseCode: "ECS 032C A02", courseName: "Implementation of Data Structures in C", open: 37, reserved: 0, waitlist: 0, units: 4, instructor: "D. Posnett", rmpRating: 2.0,
              courseNotes: "** NOT OPEN TO COMPUTER SCIENCE AND COMPUTER SCIENCE & ENGINEERING MAJORS **",
              description: "Programming in the C language. Use of basic UNIX tools. Writing good programs of increased complexity and efficiency. Implementation of data structures in C.",
              subject: "Engineering Computer Science", prerequisities: "ECS 032B C- or better", newGECourses: "SE",
              finalExam: Calendar.current.date(from: DateComponents(year: 2023, month: 12, day: 14))!,
              courseMaterials: "https://ucdavisstores.com/SelectTermDept?reg=7",
              courseDropDate: Calendar.current.date(from: DateComponents(year: 2023, month: 10, day: 24))!,
              warning: (true, "Already passed the class.")),
        
        Class(crn: 30330, courseCode: "ECS 036A 001", courseName: "Programming & Problem Solving", open: 92, reserved: 200, waitlist: 0, units: 4, instructor: "M. Butner", rmpRating: 3.7,
              courseNotes: "** PASS 1: OPEN TO COMPUTER SCIENCE, COMPUTER SCIENCE & ENGINEERING, & COMPUTER ENTINEERING MAJORS. ** \n\n ** PASS 2: OPEN TO COMPUTER SCIENCE, COMPUTER SCIENCE & ENGINEERING, COMPUTER ENGINEERING, COGNITIVE SCIENCE, APPLIED PHYSICS, PSYCHOLOGY, AND STATISTICS MAJORS. ** \n\n **RESERVED SEATS HELD FOR NEW FRESHMEN AND TRANSFER STUDENTS ** \n\n **THIS COURSE DOES NOT HAVE A WAITLIST DURING PASS 1 FOR THE FALL TERM**",
              description: "Computers and computer programming for students with some prior experience, algorithm design, and debugging. Good programming style. Use of basic UNIX tools.",
              subject: "Engineering Computer Science", prerequisities: "ECS 032A C- or better or ECS 010 C- or better; or must satisfy computer science placement exam; prior experience with basic programming concepts (variable, loops, conditional statements) required.", newGECourses: "SE",
              finalExam: Calendar.current.date(from: DateComponents(year: 2023, month: 12, day: 12))!,
              courseMaterials: "https://ucdavisstores.com/SelectTermDept?reg=7",
              courseDropDate: Calendar.current.date(from: DateComponents(year: 2023, month: 10, day: 10))!,
              warning: (true, "Already passed the class.")),
        
        Class(crn: 30331, courseCode: "ECS 036B A01", courseName: "Software Development & Object-Oriented Programming in C++", open: 52, reserved: 4, waitlist: 0, units: 4, instructor: "S. Wu", rmpRating: 3.4,
              courseNotes: "** PASS 1: OPEN TO COMPUTER SCIENCE, COMPUTER SCIENCE & ENGINEERING, COMPUTER ENGINEERING, APPLIED PHYSICS, AND COGNITIVE SCIENCE MAJORS ** \n\n **RESERVED SEATS HELD FOR NEW FRESHMEN AND TRANSFER STUDENTS ** \n\n **THIS COURSE DOES NOT HAVE A WAITLIST DURING PASS 1 FOR THE FALL TERM**",
              description: "Object-oriented programming in C++. Basic data structures and their use. Writing good programs of increased complexity and efficiency. Methods for debugging and verification.",
              subject: "Engineering Computer Science", prerequisities: "ECS 030 C- or better or ECS 036A C- or better", newGECourses: "SE",
              finalExam: Calendar.current.date(from: DateComponents(year: 2023, month: 12, day: 15))!,
              courseMaterials: "https://ucdavisstores.com/SelectTermDept?reg=7",
              courseDropDate: Calendar.current.date(from: DateComponents(year: 2023, month: 10, day: 10))!,
              warning: (true, "Already passed the class.")),
        
        Class(crn: 30332, courseCode: "ECS 036B A02", courseName: "Software Development & Object-Oriented Programming in C++", open: 53, reserved: 4, waitlist: 0, units: 4, instructor: "S. Wu", rmpRating: 3.4,
              courseNotes: "** PASS 1: OPEN TO COMPUTER SCIENCE, COMPUTER SCIENCE & ENGINEERING, COMPUTER ENGINEERING, APPLIED PHYSICS, AND COGNITIVE SCIENCE MAJORS ** \n\n **RESERVED SEATS HELD FOR NEW FRESHMEN AND TRANSFER STUDENTS ** \n\n **THIS COURSE DOES NOT HAVE A WAITLIST DURING PASS 1 FOR THE FALL TERM**",
              description: "Object-oriented programming in C++. Basic data structures and their use. Writing good programs of increased complexity and efficiency. Methods for debugging and verification.",
              subject: "Engineering Computer Science", prerequisities: "ECS 030 C- or better or ECS 036A C- or better", newGECourses: "SE",
              finalExam: Calendar.current.date(from: DateComponents(year: 2023, month: 12, day: 15))!,
              courseMaterials: "https://ucdavisstores.com/SelectTermDept?reg=7",
              courseDropDate: Calendar.current.date(from: DateComponents(year: 2023, month: 10, day: 10))!,
              warning: (true, "Already passed the class.")),
        
        Class(crn: 30333, courseCode: "ECS 036B A03", courseName: "Software Development & Object-Oriented Programming in C++", open: 51, reserved: 2, waitlist: 0, units: 4, instructor: "S. Wu", rmpRating: 3.4,
              courseNotes: "** PASS 1: OPEN TO COMPUTER SCIENCE, COMPUTER SCIENCE & ENGINEERING, COMPUTER ENGINEERING, APPLIED PHYSICS, AND COGNITIVE SCIENCE MAJORS ** \n\n **RESERVED SEATS HELD FOR NEW FRESHMEN AND TRANSFER STUDENTS ** \n\n **THIS COURSE DOES NOT HAVE A WAITLIST DURING PASS 1 FOR THE FALL TERM**",
              description: "Object-oriented programming in C++. Basic data structures and their use. Writing good programs of increased complexity and efficiency. Methods for debugging and verification.",
              subject: "Engineering Computer Science", prerequisities: "ECS 030 C- or better or ECS 036A C- or better", newGECourses: "SE",
              finalExam: Calendar.current.date(from: DateComponents(year: 2023, month: 12, day: 15))!,
              courseMaterials: "https://ucdavisstores.com/SelectTermDept?reg=7",
              courseDropDate: Calendar.current.date(from: DateComponents(year: 2023, month: 10, day: 10))!,
              warning: (true, "Already passed the class.")),
        
        Class(crn: 30334, courseCode: "ECS 036C A01", courseName: "Data Structures, Algorithms, & Programming", open: 48, reserved: 4, waitlist: 0, units: 4, instructor: "E. Solares", rmpRating: 3.9,
              courseNotes: "** PASS 1: OPEN TO COMPUTER SCIENCE, COMPUTER SCIENCE ENGINEERING, COMPUTER ENGINEERING, APPLIED PHYSICS, AND COGNITIVE SCIENCE MAJORS ONLY ** \n\n **RESERVED SEATS HELD FOR NEW FRESHMEN AND TRANSFER STUDENTS ** \n\n **THIS COURSE DOES NOT HAVE A WAITLIST DURING PASS 1 FOR THE FALL TERM**",
              description: "Design and analysis of data structures for a variety of applications; trees, heaps, searching, sorting, hashing, and graphs. Extensive programming.",
              subject: "Engineering Computer Science", prerequisities: "(ECS 040 C- or better or ECS 036B C- or better); ECS 020 C- or better", newGECourses: "SE",
              finalExam: Calendar.current.date(from: DateComponents(year: 2023, month: 12, day: 13))!,
              courseMaterials: "https://ucdavisstores.com/SelectTermDept?reg=7",
              courseDropDate: Calendar.current.date(from: DateComponents(year: 2023, month: 10, day: 10))!,
              warning: (true, "Already passed the class.")),
        
        Class(crn: 30335, courseCode: "ECS 036C A02", courseName: "Data Structures, Algorithms, & Programming", open: 50, reserved: 4, waitlist: 0, units: 4, instructor: "E. Solares", rmpRating: 3.9,
              courseNotes: "** PASS 1: OPEN TO COMPUTER SCIENCE, COMPUTER SCIENCE ENGINEERING, COMPUTER ENGINEERING, APPLIED PHYSICS, AND COGNITIVE SCIENCE MAJORS ONLY ** \n\n **RESERVED SEATS HELD FOR NEW FRESHMEN AND TRANSFER STUDENTS ** \n\n **THIS COURSE DOES NOT HAVE A WAITLIST DURING PASS 1 FOR THE FALL TERM**",
              description: "Design and analysis of data structures for a variety of applications; trees, heaps, searching, sorting, hashing, and graphs. Extensive programming.",
              subject: "Engineering Computer Science", prerequisities: "(ECS 040 C- or better or ECS 036B C- or better); ECS 020 C- or better", newGECourses: "SE",
              finalExam: Calendar.current.date(from: DateComponents(year: 2023, month: 12, day: 13))!,
              courseMaterials: "https://ucdavisstores.com/SelectTermDept?reg=7",
              courseDropDate: Calendar.current.date(from: DateComponents(year: 2023, month: 10, day: 10))!,
              warning: (true, "Already passed the class.")),
        
        Class(crn: 30337, courseCode: "ECS 050 A01", courseName: "Computer Organization & Machine-Dependent Programming", open: 48, reserved: 4, waitlist: 0, units: 4, instructor: "J. Porquet", rmpRating: 4.5,
              courseNotes: "** PASS ONE RESTRICTED TO COMPUTER SCIENCE AND COMPUTER SCIENCE & ENGINEERING MAJORS ONLY ** \n\n **RESERVED SEATS HELD FOR NEW FRESHMEN AND TRANSFER STUDENTS ** \n\n **THIS COURSE DOES NOT HAVE A WAITLIST DURING PASS 1 FOR THE FALL TERM**",
              description: "Comparative study of different hardware architectures via programming in the assembly languages of various machines. Role of system software in producing an abstract machine. Introduction to I/O devices and programming.",
              subject: "Engineering Computer Science", prerequisities: "ECS 040 C- or better or ECS 034 C- or better or ECS 036B C- or better", newGECourses: "SE",
              finalExam: Calendar.current.date(from: DateComponents(year: 2023, month: 12, day: 14))!,
              courseMaterials: "https://ucdavisstores.com/SelectTermDept?reg=7",
              courseDropDate: Calendar.current.date(from: DateComponents(year: 2023, month: 10, day: 10))!,
              warning: (true, "Already passed the class.")),
        
        Class(crn: 52325, courseCode: "ECS 050 A02", courseName: "Computer Organization & Machine-Dependent Programming", open: 48, reserved: 4, waitlist: 0, units: 4, instructor: "J. Porquet", rmpRating: 4.5,
              courseNotes: "** PASS ONE RESTRICTED TO COMPUTER SCIENCE AND COMPUTER SCIENCE & ENGINEERING MAJORS ONLY ** \n\n **RESERVED SEATS HELD FOR NEW FRESHMEN AND TRANSFER STUDENTS ** \n\n **THIS COURSE DOES NOT HAVE A WAITLIST DURING PASS 1 FOR THE FALL TERM**",
              description: "Comparative study of different hardware architectures via programming in the assembly languages of various machines. Role of system software in producing an abstract machine. Introduction to I/O devices and programming.",
              subject: "Engineering Computer Science", prerequisities: "ECS 040 C- or better or ECS 034 C- or better or ECS 036B C- or better", newGECourses: "SE",
              finalExam: Calendar.current.date(from: DateComponents(year: 2023, month: 12, day: 14))!,
              courseMaterials: "https://ucdavisstores.com/SelectTermDept?reg=7",
              courseDropDate: Calendar.current.date(from: DateComponents(year: 2023, month: 10, day: 10))!,
              warning: (true, "Already passed the class.")),
        
        Class(crn: 00000, courseCode: "ECS 092", courseName: "Internship in Computer Science", open: 0, reserved: 0, waitlist: 0, units: 1, instructor: "The Staff", rmpRating: 0.0,
              courseNotes: "",
              description: "Supervised work experience in computer science.",
              subject: "Engineering Computer Science", prerequisities: "Lower division standing; project approval prior to period of internship.", newGECourses: "N/A",
              finalExam: Calendar.current.date(from: DateComponents(year: 2023, month: 12, day: 12))!,
              courseMaterials: "https://ucdavisstores.com/SelectTermDept?reg=7",
              courseDropDate: Calendar.current.date(from: DateComponents(year: 2023, month: 10, day: 10))!,
              warning: (false, "")),
        
        Class(crn: 00000, courseCode: "ECS 099", courseName: "Special Study for Lower Division Students", open: 0, reserved: 0, waitlist: 0, units: 1, instructor: "The Staff", rmpRating: 0.0,
              courseNotes: "",
              description: "Special study for lower division students.",
              subject: "Engineering Computer Science", prerequisities: "Consent of Instructor.", newGECourses: "",
              finalExam: Calendar.current.date(from: DateComponents(year: 2023, month: 12, day: 12))!,
              courseMaterials: "https://ucdavisstores.com/SelectTermDept?reg=7",
              courseDropDate: Calendar.current.date(from: DateComponents(year: 2023, month: 10, day: 10))!,
              warning: (false, "")),
        
        Class(crn: 30442, courseCode: "ECS 120 A01", courseName: "Theory of Computation", open: 0, reserved: 0, waitlist: 18, units: 4, instructor: "Y. Frid", rmpRating: 3.8,
              courseNotes: "** PASS ONE: OPEN TO COMPUTER ENGINEERING, COMPUTER SCIENCE & ENGINEERING, COMPUTER SCIENCE, AND COGNITIVE SCIENCE **",
              description: "Fundamental ideas in the theory of computation, including formal languages, computability and complexity. Reducibility among computational problems.",
              subject: "Engineering Computer Science", prerequisities: "(ECS 020 or MAT 108); (ECS 32B or ECS 36C recommended)", newGECourses: "QL, SE",
              finalExam: Calendar.current.date(from: DateComponents(year: 2023, month: 12, day: 13))!,
              courseMaterials: "https://ucdavisstores.com/SelectTermDept?reg=7",
              courseDropDate: Calendar.current.date(from: DateComponents(year: 2023, month: 10, day: 10))!,
              warning: (false, "")),
        
        Class(crn: 30443, courseCode: "ECS 120 A02", courseName: "Theory of Computation", open: 0, reserved: 0, waitlist: 21, units: 4, instructor: "Y. Frid", rmpRating: 3.8,
              courseNotes: "** PASS ONE: OPEN TO COMPUTER ENGINEERING, COMPUTER SCIENCE & ENGINEERING, COMPUTER SCIENCE, AND COGNITIVE SCIENCE **",
              description: "Fundamental ideas in the theory of computation, including formal languages, computability and complexity. Reducibility among computational problems.",
              subject: "Engineering Computer Science", prerequisities: "(ECS 020 or MAT 108); (ECS 32B or ECS 36C recommended)", newGECourses: "QL, SE",
              finalExam: Calendar.current.date(from: DateComponents(year: 2023, month: 12, day: 13))!,
              courseMaterials: "https://ucdavisstores.com/SelectTermDept?reg=7",
              courseDropDate: Calendar.current.date(from: DateComponents(year: 2023, month: 10, day: 10))!,
              warning: (false, "")),
        
        Class(crn: 30444, courseCode: "ECS 120 A03", courseName: "Theory of Computation", open: 0, reserved: 0, waitlist: 20, units: 4, instructor: "Y. Frid", rmpRating: 3.8,
              courseNotes: "** PASS ONE: OPEN TO COMPUTER ENGINEERING, COMPUTER SCIENCE & ENGINEERING, COMPUTER SCIENCE, AND COGNITIVE SCIENCE **",
              description: "Fundamental ideas in the theory of computation, including formal languages, computability and complexity. Reducibility among computational problems.",
              subject: "Engineering Computer Science", prerequisities: "(ECS 020 or MAT 108); (ECS 32B or ECS 36C recommended)", newGECourses: "QL, SE",
              finalExam: Calendar.current.date(from: DateComponents(year: 2023, month: 12, day: 13))!,
              courseMaterials: "https://ucdavisstores.com/SelectTermDept?reg=7",
              courseDropDate: Calendar.current.date(from: DateComponents(year: 2023, month: 10, day: 10))!,
              warning: (false, "")),
        
        Class(crn: 30445, courseCode: "ECS 122A A01", courseName: "Algorithm Design & Analysis", open: 6, reserved: 20, waitlist: 0, units: 4, instructor: "Y. Frid", rmpRating: 3.8,
              courseNotes: "** PASS 1: OPEN TO COMPUTER SCIENCE, COMPUTER SCIENCE & ENGINEERING, COMPUTER ENGINEERING, AND APPLIED PHYSICS MAJORS ONLY ** \n\n **RESERVED SEATS HELD FOR NEW FRESHMEN AND TRANSFER STUDENTS ** \n\n **THIS COURSE DOES NOT HAVE A WAITLIST DURING PASS 1 FOR THE FALL TERM**",
              description: "Complexity of algorithms, bounds on complexity, analysis methods. Searching, sorting, pattern matching, graph algorithms. Algorithm design techniques: divide-conquer, greedy, dynamic programming. Approximation methods. NP-complete problems.",
              subject: "Engineering Computer Science", prerequisities: "ECS 020; (ECS 060 or ECS 032B or ECS 036C)", newGECourses: "SE",
              finalExam: Calendar.current.date(from: DateComponents(year: 2023, month: 12, day: 15))!,
              courseMaterials: "https://ucdavisstores.com/SelectTermDept?reg=7",
              courseDropDate: Calendar.current.date(from: DateComponents(year: 2023, month: 10, day: 10))!,
              warning: (true, "Already passed the class.")),
        
        Class(crn: 30446, courseCode: "ECS 122A A02", courseName: "Algorithm Design & Analysis", open: 19, reserved: 20, waitlist: 0, units: 4, instructor: "Y. Frid", rmpRating: 3.8,
              courseNotes: "** PASS 1: OPEN TO COMPUTER SCIENCE, COMPUTER SCIENCE & ENGINEERING, COMPUTER ENGINEERING, AND APPLIED PHYSICS MAJORS ONLY ** \n\n **RESERVED SEATS HELD FOR NEW FRESHMEN AND TRANSFER STUDENTS ** \n\n **THIS COURSE DOES NOT HAVE A WAITLIST DURING PASS 1 FOR THE FALL TERM**",
              description: "Complexity of algorithms, bounds on complexity, analysis methods. Searching, sorting, pattern matching, graph algorithms. Algorithm design techniques: divide-conquer, greedy, dynamic programming. Approximation methods. NP-complete problems.",
              subject: "Engineering Computer Science", prerequisities: "ECS 020; (ECS 060 or ECS 032B or ECS 036C)", newGECourses: "SE",
              finalExam: Calendar.current.date(from: DateComponents(year: 2023, month: 12, day: 15))!,
              courseMaterials: "https://ucdavisstores.com/SelectTermDept?reg=7",
              courseDropDate: Calendar.current.date(from: DateComponents(year: 2023, month: 10, day: 10))!,
              warning: (true, "Already passed the class.")),
        
        Class(crn: 30447, courseCode: "ECS 122A A03", courseName: "Algorithm Design & Analysis", open: 14, reserved: 20, waitlist: 0, units: 4, instructor: "Y. Frid", rmpRating: 3.8,
              courseNotes: "** PASS 1: OPEN TO COMPUTER SCIENCE, COMPUTER SCIENCE & ENGINEERING, COMPUTER ENGINEERING, AND APPLIED PHYSICS MAJORS ONLY ** \n\n **RESERVED SEATS HELD FOR NEW FRESHMEN AND TRANSFER STUDENTS ** \n\n **THIS COURSE DOES NOT HAVE A WAITLIST DURING PASS 1 FOR THE FALL TERM**",
              description: "Complexity of algorithms, bounds on complexity, analysis methods. Searching, sorting, pattern matching, graph algorithms. Algorithm design techniques: divide-conquer, greedy, dynamic programming. Approximation methods. NP-complete problems.",
              subject: "Engineering Computer Science", prerequisities: "ECS 020; (ECS 060 or ECS 032B or ECS 036C)", newGECourses: "SE",
              finalExam: Calendar.current.date(from: DateComponents(year: 2023, month: 12, day: 15))!,
              courseMaterials: "https://ucdavisstores.com/SelectTermDept?reg=7",
              courseDropDate: Calendar.current.date(from: DateComponents(year: 2023, month: 10, day: 10))!,
              warning: (true, "Already passed the class.")),
        
        Class(crn: 52326, courseCode: "ECS 130 001", courseName: "Scientific Computation", open: 0, reserved: 0, waitlist: 19, units: 4, instructor: "F. Panetta", rmpRating: 5.0,
              courseNotes: "** PASS 1: OPEN TO COMPUTER SCIENCE AND COMPUTER SCIENCE & ENGINEERING MAJORS ONLY**",
              description: "Matrix-vector approach using MATLAB for floating-point arithmetic, error analysis, data interpolation, least squares data fitting, quadrature, zeros, optimization and matrix eigenvalues and singular values. Parallel computing for matrix operations and essential matrix factorizations.",
              subject: "Engineering Computer Science", prerequisities: "(ECS 030 or ENG 006 or ECS 032A or ECS 010 or ECS 036A); (MAT 022A or MAT 027A or MAT 067)", newGECourses: "SE",
              finalExam: Calendar.current.date(from: DateComponents(year: 2023, month: 12, day: 12))!,
              courseMaterials: "https://ucdavisstores.com/SelectTermDept?reg=7",
              courseDropDate: Calendar.current.date(from: DateComponents(year: 2023, month: 10, day: 10))!,
              warning: (false, "")),
        
        Class(crn: 30451, courseCode: "ECS 132 001", courseName: "Probability & Statistical Modeling for Computer Science", open: 128, reserved: 0, waitlist: 0, units: 4, instructor: "V. Bhaskar", rmpRating: 2.0,
              courseNotes: "** PASS 1: OPEN TO COMPUTER SCIENCE, AND COMPUTER SCIENCE ENGINEERING MAJORS **",
              description: "Univariate and multivariate distributions. Estimation and model building. Markov/Hidden Markov models. Applications to data mining, networks, security, software engineering and bioinformatics.",
              subject: "Engineering Computer Science", prerequisities: "(ECS 040 or ECS 034 or ECS 036B); ECS 020; MAT 021C; (MAT 022A or MAT 027A or MAT 067)", newGECourses: "QL, SE",
              finalExam: Calendar.current.date(from: DateComponents(year: 2023, month: 12, day: 13))!,
              courseMaterials: "https://ucdavisstores.com/SelectTermDept?reg=7",
              courseDropDate: Calendar.current.date(from: DateComponents(year: 2023, month: 10, day: 10))!,
              warning: (false, "")),
        
        Class(crn: 30452, courseCode: "ECS 140A 001", courseName: "Programming Languages", open: 30, reserved: 0, waitlist: 0, units: 4, instructor: "V. Bhaskar", rmpRating: 2.0,
              courseNotes: "** PASS 1: OPEN TO COMPUTER SCIENCE AND COMPUTER SCIENCE & ENGINEERING MAJORS ONLY**",
              description: "Syntactic definition of programming languages. Introduction to programming language features including variables, data types, data abstraction, object-orientedness, scoping, parameter disciplines, exception handling. Non-imperative programming languages. Comparative study of several high-level programming languages.",
              subject: "Engineering Computer Science", prerequisities: "ECS 050; ECS 020; (ECS 034 or ECS 036C); ECS 150 recommended.", newGECourses: "SE",
              finalExam: Calendar.current.date(from: DateComponents(year: 2023, month: 12, day: 15))!,
              courseMaterials: "https://ucdavisstores.com/SelectTermDept?reg=7",
              courseDropDate: Calendar.current.date(from: DateComponents(year: 2023, month: 10, day: 10))!,
              warning: (false, "")),
        
        Class(crn: 30453, courseCode: "ECS 150 001", courseName: "Operating Systems & System Programming", open: 205, reserved: 0, waitlist: 0, units: 4, instructor: "D. Posnett", rmpRating: 2.0,
              courseNotes: "** PASS 1: OPEN TO COMPUTER SCIENCE AND ENGINEERING AND COMPUTER ENGINEERING MAJORS ONLY ** \n\n ** PASS 2: OPEN TO COMPUTER SCIENCE MAJORS ONLY **",
              description: "Basic concepts of operating systems and system programming. Processes and interprocess communication/synchronization; virtual memory, program loading and linking; file and I/O subsystems; utility programs. Study of a real operating system.",
              subject: "Engineering Computer Science", prerequisities: "(ECS 034 or ECS 036C or ECS 060); (ECS 154A or EEC 170)", newGECourses: "SE",
              finalExam: Calendar.current.date(from: DateComponents(year: 2023, month: 12, day: 11))!,
              courseMaterials: "https://ucdavisstores.com/SelectTermDept?reg=7",
              courseDropDate: Calendar.current.date(from: DateComponents(year: 2023, month: 10, day: 10))!,
              warning: (false, "")),
        
        Class(crn: 30454, courseCode: "ECS 152A A01", courseName: "Computer Networks", open: 21, reserved: 0, waitlist: 0, units: 4, instructor: "M. Shafiq", rmpRating: 3.3,
              courseNotes: "** PASS 1: OPEN TO COMPUTER SCIENCE AND COMPUTER SCIENCE AND ENGINEERING MAJORS **",
              description: "Overview of computer networks, TCP/IP protocol suite, computer-networking applications and protocols, transport-layer protocols, network architectures, Internet Protocol (IP), routing, link-layer protocols, local area and wireless networks, medium access control, physical aspects of data transmission, and network-performance analysis.",
              subject: "Engineering Computer Science", prerequisities: "(ECS 060 or ECS 032B or ECS 036C); (ECS 132 or EEC 161 or MAT 135A or STA 131A or STA 120 or STA 032)", newGECourses: "SE",
              finalExam: Calendar.current.date(from: DateComponents(year: 2023, month: 12, day: 13))!,
              courseMaterials: "https://ucdavisstores.com/SelectTermDept?reg=7",
              courseDropDate: Calendar.current.date(from: DateComponents(year: 2023, month: 10, day: 10))!,
              warning: (false, "")),
        
        Class(crn: 30455, courseCode: "ECS 152A A02", courseName: "Computer Networks", open: 18, reserved: 0, waitlist: 0, units: 4, instructor: "M. Shafiq", rmpRating: 3.3,
              courseNotes: "** PASS 1: OPEN TO COMPUTER SCIENCE AND COMPUTER SCIENCE AND ENGINEERING MAJORS **",
              description: "Overview of computer networks, TCP/IP protocol suite, computer-networking applications and protocols, transport-layer protocols, network architectures, Internet Protocol (IP), routing, link-layer protocols, local area and wireless networks, medium access control, physical aspects of data transmission, and network-performance analysis.",
              subject: "Engineering Computer Science", prerequisities: "(ECS 060 or ECS 032B or ECS 036C); (ECS 132 or EEC 161 or MAT 135A or STA 131A or STA 120 or STA 032)", newGECourses: "SE",
              finalExam: Calendar.current.date(from: DateComponents(year: 2023, month: 12, day: 13))!,
              courseMaterials: "https://ucdavisstores.com/SelectTermDept?reg=7",
              courseDropDate: Calendar.current.date(from: DateComponents(year: 2023, month: 10, day: 10))!,
              warning: (false, "")),
        
        Class(crn: 30456, courseCode: "ECS 152A A03", courseName: "Computer Networks", open: 20, reserved: 0, waitlist: 0, units: 4, instructor: "M. Shafiq", rmpRating: 3.3,
              courseNotes: "** PASS 1: OPEN TO COMPUTER SCIENCE AND COMPUTER SCIENCE AND ENGINEERING MAJORS **",
              description: "Overview of computer networks, TCP/IP protocol suite, computer-networking applications and protocols, transport-layer protocols, network architectures, Internet Protocol (IP), routing, link-layer protocols, local area and wireless networks, medium access control, physical aspects of data transmission, and network-performance analysis.",
              subject: "Engineering Computer Science", prerequisities: "(ECS 060 or ECS 032B or ECS 036C); (ECS 132 or EEC 161 or MAT 135A or STA 131A or STA 120 or STA 032)", newGECourses: "SE",
              finalExam: Calendar.current.date(from: DateComponents(year: 2023, month: 12, day: 13))!,
              courseMaterials: "https://ucdavisstores.com/SelectTermDept?reg=7",
              courseDropDate: Calendar.current.date(from: DateComponents(year: 2023, month: 10, day: 10))!,
              warning: (false, "")),
        
        Class(crn: 30457, courseCode: "ECS 154A 001", courseName: "Computer Architecture", open: 0, reserved: 120, waitlist: 0, units: 4, instructor: "M. Butner", rmpRating: 3.7,
              courseNotes: "** OPEN TO COMPUTER SCIENCE AND COMPUTER SCIENCE & ENGINEERING MAJORS ** \n\n **RESERVED SEATS HELD FOR NEW FRESHMEN AND TRANSFER STUDENTS ** \n\n **THIS COURSE DOES NOT HAVE A WAITLIST DURING PASS 1 FOR THE FALL TERM**",
              description: "Introduction to digital design. Interfacing of devices for I/O, memory and memory management. Input/output programming, via wait loops, hardware interrupts and calls to operating system services. Hardware support for operating systems software.",
              subject: "Engineering Computer Science", prerequisities: "ECS 050 or EEC 070", newGECourses: "SE",
              finalExam: Calendar.current.date(from: DateComponents(year: 2023, month: 12, day: 13))!,
              courseMaterials: "https://ucdavisstores.com/SelectTermDept?reg=7",
              courseDropDate: Calendar.current.date(from: DateComponents(year: 2023, month: 10, day: 10))!,
              warning: (true, "Already passed the class.")),
        
        Class(crn: 30458, courseCode: "ECS 160 001", courseName: "Software Engineering", open: 11, reserved: 0, waitlist: 0, units: 4, instructor: "D. Posnett", rmpRating: 2.0,
              courseNotes: "** PASS 1: OPEN TO COMPUTER SCIENCE, AND COMPUTER SCIENCE AND ENGINEERING MAJORS ONLY **",
              description: "Requirements, specification, design, implementation, testing, and verification of large software systems. Study and use of software engineering methodologies.",
              subject: "Engineering Computer Science", prerequisities: "ECS 140A; extensive programming experience recommended.", newGECourses: "SE",
              finalExam: Calendar.current.date(from: DateComponents(year: 2023, month: 12, day: 13))!,
              courseMaterials: "https://ucdavisstores.com/SelectTermDept?reg=7",
              courseDropDate: Calendar.current.date(from: DateComponents(year: 2023, month: 10, day: 10))!,
              warning: (true, "Haven't fulfilled prerequisites.")),
        
        Class(crn: 30459, courseCode: "ECS 171 001", courseName: "Machine Learning", open: 12, reserved: 0, waitlist: 0, units: 4, instructor: "S. Rafatirad", rmpRating: 3.9,
              courseNotes: "** PASS 1: OPEN TO COMPUTER SCIENCE, COMPUTER SCIENCE & ENGINEERING, AND COGNITIVE SCIENCE MAJORS ONLY ** \n\n ** PASS 2: OPEN TO UNDERGRADUATE STUDENTS ONLY **",
              description: "Introduction to machine learning. Supervised & unsupervised learning, including classification, dimensionality reduction, regression & clustering using modern machine learning methods. Applications of machine learning to other fields.",
              subject: "Engineering Computer Science", prerequisities: "(ECS 032B or ECS 036C); (STA 032 or STA 131A or ECS 132); (MAT 022A or MAT 027A)", newGECourses: "SE",
              finalExam: Calendar.current.date(from: DateComponents(year: 2023, month: 12, day: 13))!,
              courseMaterials: "https://ucdavisstores.com/SelectTermDept?reg=7",
              courseDropDate: Calendar.current.date(from: DateComponents(year: 2023, month: 10, day: 10))!,
              warning: (true, "Haven't fulfilled prerequisites.")),
        
        Class(crn: 30460, courseCode: "ECS 175 001", courseName: "Computer Graphics", open: 60, reserved: 0, waitlist: 0, units: 4, instructor: "K. Ma", rmpRating: 1.8,
              courseNotes: "** PASS 1: OPEN TO COMPUTER SCIENCE AND COMPUTER SCIENCE ENGINEERING MAJORS **",
              description: "Principles of computer graphics, with a focus on interactive systems. Current graphics hardware, elementary operations in two-and three-dimensional space, geometric transformations, camera models and interaction, graphics system design, standard graphics APIs, individual projects.",
              subject: "Engineering Computer Science", prerequisities: "(ECS 060 or ECS 034 or ECS 036C); (MAT 022A or MAT 027A or MAT 067)", newGECourses: "SE",
              finalExam: Calendar.current.date(from: DateComponents(year: 2023, month: 12, day: 12))!,
              courseMaterials: "https://ucdavisstores.com/SelectTermDept?reg=7",
              courseDropDate: Calendar.current.date(from: DateComponents(year: 2023, month: 10, day: 10))!,
              warning: (false, "")),
        
        Class(crn: 30462, courseCode: "ECS 188 001", courseName: "Ethics in an Age of Technology", open: 24, reserved: 0, waitlist: 0, units: 4, instructor: "K. Eiselt", rmpRating: 3.4,
              courseNotes: "** PASS 1:OPEN TO COMPUTER SCIENCE AND ENGINEERING MAJORS ** \n\n** PASS 2:OPEN TO COMPUTER SCIENCE & ENGINEERING AND COMPUTER SCIENCE MAJORS ** \n\n** MANDATORY ATTENDANCE ON THE FIRST DAY OF INSTRUCTION **",
              description: "Foundations of ethics. Views of technology. Technology and human values. Costs and benefits of technology. Character of technological change. Social context of work in computer science and engineering.",
              subject: "Engineering Computer Science", prerequisities: "Upper division standing.", newGECourses: "SL, SS, WE",
              finalExam: Calendar.current.date(from: DateComponents(year: 2023, month: 12, day: 14))!,
              courseMaterials: "https://ucdavisstores.com/SelectTermDept?reg=7",
              courseDropDate: Calendar.current.date(from: DateComponents(year: 2023, month: 10, day: 10))!,
              warning: (false, ""))
    ]
}
